# rustfmt configuration for ailoop
# Constitution requirement: 100-character line limits

max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
indent_style = "Block"
width_heuristics = "Scaled"
single_line_if_else_max_width = 50
fn_args_layout = "Tall"
fn_params_layout = "Tall"
fn_single_line = false
where_single_line = false
struct_lit_single_line = false
array_width = 60
chain_width = 60
single_line_let_else_max_width = 50
reorder_impl_items = false
reorder_imports = true
remove_nested_parens = true
normalize_comments = true
format_code_in_doc_comments = true
format_strings = true
empty_item_single_line = true
imports_granularity = "Module"
imports_indent = "Block"
imports_layout = "Mixed"
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
use_try_shorthand = true
use_await_macro = true
use_block_indent = true